<?php
/**
 * Emit the WordPress import file (WXR 1.2) for the AK site.
 *
 * Generated by script rather than written by hand for one load-bearing
 * reason: Contact Form 7 stores its mail configuration as PHP-SERIALIZED
 * arrays in postmeta, and serialized PHP counts string lengths in BYTES.
 * One miscounted length and the importer silently drops the meta, the form
 * imports with no recipient, and nobody notices until a lead goes nowhere.
 * serialize() cannot miscount.
 *
 * Run: php scripts/build-wxr.php > wordpress/import/ak-content.xml
 */

date_default_timezone_set( 'UTC' );

const SITE  = 'https://akbrand.studio';
const EMAIL = 'hello@akbrand.studio';
const NOW   = '2026-08-31 12:00:00';

$ids = 1000; // deterministic, far above a fresh install's range

function esc_xml_text( $s ) {
	return htmlspecialchars( (string) $s, ENT_XML1 | ENT_QUOTES, 'UTF-8' );
}

function cdata( $s ) {
	// A literal "]]>" inside CDATA must be split; nothing here contains one,
	// but the guard costs nothing and import files get edited by hand later.
	return '<![CDATA[' . str_replace( ']]>', ']]]]><![CDATA[>', (string) $s ) . ']]>';
}

function meta_row( $key, $value ) {
	return "\t\t<wp:postmeta>\n\t\t\t<wp:meta_key>" . cdata( $key ) . "</wp:meta_key>\n\t\t\t<wp:meta_value>" . cdata( $value ) . "</wp:meta_value>\n\t\t</wp:postmeta>\n";
}

/**
 * One <item>. $args: title, slug, type, content, excerpt, status, parent,
 * menu_order, meta (assoc), terms (list of [domain, slug, name]), date.
 */
function item( $args ) {
	global $ids;
	$id      = ++$ids;
	$title   = $args['title'];
	$slug    = $args['slug'];
	$type    = $args['type'];
	$content = isset( $args['content'] ) ? $args['content'] : '';
	$excerpt = isset( $args['excerpt'] ) ? $args['excerpt'] : '';
	$status  = isset( $args['status'] ) ? $args['status'] : 'publish';
	$parent  = isset( $args['parent'] ) ? (int) $args['parent'] : 0;
	$order   = isset( $args['menu_order'] ) ? (int) $args['menu_order'] : 0;
	$date    = isset( $args['date'] ) ? $args['date'] : NOW;
	// Pages and posts live at /slug/; portfolio rewrites to /work/slug/.
	$link    = SITE . '/' . ( 'portfolio' === $type ? 'work/' . $slug : $slug ) . '/';

	$out  = "\t<item>\n";
	$out .= "\t\t<title>" . cdata( $title ) . "</title>\n";
	$out .= "\t\t<link>" . esc_xml_text( $link ) . "</link>\n";
	$out .= "\t\t<pubDate>" . esc_xml_text( gmdate( 'D, d M Y H:i:s +0000', strtotime( $date ) ) ) . "</pubDate>\n";
	$out .= "\t\t<dc:creator>" . cdata( 'akstudio' ) . "</dc:creator>\n";
	$out .= "\t\t<guid isPermaLink=\"false\">" . esc_xml_text( SITE . '/?p=' . $id ) . "</guid>\n";
	$out .= "\t\t<description></description>\n";
	$out .= "\t\t<content:encoded>" . cdata( $content ) . "</content:encoded>\n";
	$out .= "\t\t<excerpt:encoded>" . cdata( $excerpt ) . "</excerpt:encoded>\n";
	$out .= "\t\t<wp:post_id>" . $id . "</wp:post_id>\n";
	$out .= "\t\t<wp:post_date>" . cdata( $date ) . "</wp:post_date>\n";
	$out .= "\t\t<wp:post_date_gmt>" . cdata( $date ) . "</wp:post_date_gmt>\n";
	$out .= "\t\t<wp:post_modified>" . cdata( $date ) . "</wp:post_modified>\n";
	$out .= "\t\t<wp:post_modified_gmt>" . cdata( $date ) . "</wp:post_modified_gmt>\n";
	$out .= "\t\t<wp:comment_status>" . cdata( 'closed' ) . "</wp:comment_status>\n";
	$out .= "\t\t<wp:ping_status>" . cdata( 'closed' ) . "</wp:ping_status>\n";
	$out .= "\t\t<wp:post_name>" . cdata( $slug ) . "</wp:post_name>\n";
	$out .= "\t\t<wp:status>" . cdata( $status ) . "</wp:status>\n";
	$out .= "\t\t<wp:post_parent>" . $parent . "</wp:post_parent>\n";
	$out .= "\t\t<wp:menu_order>" . $order . "</wp:menu_order>\n";
	$out .= "\t\t<wp:post_type>" . cdata( $type ) . "</wp:post_type>\n";
	$out .= "\t\t<wp:post_password></wp:post_password>\n";
	$out .= "\t\t<wp:is_sticky>0</wp:is_sticky>\n";

	if ( ! empty( $args['terms'] ) ) {
		foreach ( $args['terms'] as $t ) {
			$out .= "\t\t<category domain=\"" . esc_xml_text( $t[0] ) . "\" nicename=\"" . esc_xml_text( $t[1] ) . '">' . cdata( $t[2] ) . "</category>\n";
		}
	}
	if ( ! empty( $args['meta'] ) ) {
		foreach ( $args['meta'] as $k => $v ) {
			$out .= meta_row( $k, $v );
		}
	}
	// Ownership markers: the theme's import_end handler uses these to
	// reclaim canonical slugs from pre-existing pages and to know which
	// content is NOT ours when tidying the old site away.
	$out .= meta_row( '_ak_import', '1' );
	$out .= meta_row( '_ak_slug', $slug );
	$out .= "\t</item>\n";
	return array( $id, $out );
}

$items = '';

/* ── Pages ─────────────────────────────────────────────────────────────── */

$pages = array(
	array( 'Home', 'home', '', 1 ),
	array( 'Work', 'work', 'page-templates/template-ak-page.php', 2 ),
	array( 'Services', 'services', 'page-templates/template-services.php', 3 ),
	array( 'Journal', 'journal', '', 4 ),
	array( 'About', 'about', 'page-templates/template-about.php', 5 ),
	array( 'Contact', 'contact', 'page-templates/template-contact.php', 6 ),
);

$page_ids = array();
foreach ( $pages as $p ) {
	$meta = array();
	if ( $p[2] ) {
		$meta['_wp_page_template'] = $p[2];
	}
	// Home renders via front-page.php and Journal via home.php once assigned
	// by the activation hook — their content can stay empty. The Work page
	// exists only as a menu anchor when the CPT archive handles /work.
	list( $id, $xml ) = item(
		array(
			'title'      => $p[0],
			'slug'       => $p[1],
			'type'       => 'page',
			'menu_order' => $p[3],
			'content'    => 'work' === $p[1]
				? '<!-- This page is a fallback: the Work archive at /work/ is rendered by the portfolio post type. -->'
				: '',
			'meta'       => $meta,
		)
	);
	$page_ids[ $p[1] ] = $id;
	$items            .= $xml;
}

/* ── Case studies (placeholders — the founders replace these) ──────────── */

$cases = array(
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-collection-launch',
		'headline' => 'A first collection, shown in London.',
		'category' => 'Collection launch',
		'year'     => '2026',
		'movements' => 'Strategy, Identity, Production',
		'summary'  => 'Placeholder. A designer with a finished collection and no route to an audience. Position, identity and a runway slot inside one season — replace this text with the real project.',
		'measures' => array( array( 'key' => 'LOOKS', 'value' => '24' ), array( 'key' => 'PRESS', 'value' => '38' ), array( 'key' => 'RUNWAY', 'value' => 'LDN' ) ),
		'chapters' => array(
			array( 'title' => 'The position', 'body' => 'Placeholder chapter. Describe what the brand was saying about itself before, and what it says now.', 'mkey' => 'DECK', 'mval' => '1 page' ),
			array( 'title' => 'The show', 'body' => 'Placeholder chapter. Describe the production — the venue, the casting, the running order, the press list.', 'mkey' => 'LOOKS', 'mval' => '24' ),
			array( 'title' => 'The coverage', 'body' => 'Placeholder chapter. Describe what the show produced afterwards: press, stockists, follow-on work.', 'mkey' => 'PRESS', 'mval' => '38 titles' ),
		),
	),
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-brand-identity',
		'headline' => 'An identity built to survive the feed.',
		'category' => 'Brand identity',
		'year'     => '2026',
		'movements' => 'Strategy, Identity',
		'summary'  => 'Placeholder. An identity drawn at ad size first and at backdrop size second — replace with the real project.',
		'measures' => array( array( 'key' => 'MARKS', 'value' => '3' ), array( 'key' => 'SCALE', 'value' => '4:5 → 6m' ) ),
		'chapters' => array(
			array( 'title' => 'Drawn at ad size', 'body' => 'Placeholder chapter. Describe why the identity was designed for the crop it would actually live in.', 'mkey' => 'CROP', 'mval' => '4:5 first' ),
			array( 'title' => 'The system', 'body' => 'Placeholder chapter. Describe the guidelines, the type, the colour and how the team uses it without you.', 'mkey' => '', 'mval' => '' ),
		),
		'position' => array(
			'statement' => 'Placeholder positioning line — replace with the sentence this brand actually arrived at.',
			'rejected'  => array( 'Placeholder alternative one — the safe version', 'Placeholder alternative two — the category version', 'Placeholder alternative three — the trend version' ),
		),
	),
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-personal-brand',
		'headline' => 'A founder who stopped hiding behind the brand.',
		'category' => 'Personal brand',
		'year'     => '2025',
		'movements' => 'Strategy, Presence',
		'summary'  => 'Placeholder. Personal brand strategy for a founder whose company was better known than they were.',
		'measures' => array( array( 'key' => 'AUDIENCE', 'value' => '×4' ), array( 'key' => 'SPEAKING', 'value' => '6' ) ),
		'chapters' => array(
			array( 'title' => 'The position', 'body' => 'Placeholder chapter. Describe what the founder stands for and how it was found.', 'mkey' => '', 'mval' => '' ),
			array( 'title' => 'The channels', 'body' => 'Placeholder chapter. Describe where that position was put to work.', 'mkey' => 'AUDIENCE', 'mval' => '×4' ),
		),
	),
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-website',
		'headline' => 'A store that finally looked like the clothes.',
		'category' => 'E-commerce',
		'year'     => '2025',
		'movements' => 'Identity, Presence',
		'summary'  => 'Placeholder. A website and online store rebuilt around the brand rather than around a template.',
		'measures' => array( array( 'key' => 'LCP', 'value' => '0.9s' ), array( 'key' => 'CVR', 'value' => '+2.4pp' ) ),
		'chapters' => array(
			array( 'title' => 'The rebuild', 'body' => 'Placeholder chapter. Describe what the old site got wrong and what replaced it.', 'mkey' => 'LCP', 'mval' => '3.8s → 0.9s' ),
			array( 'title' => 'The promotion', 'body' => 'Placeholder chapter. Describe the digital campaigns that filled it.', 'mkey' => 'CVR', 'mval' => '+2.4pp' ),
		),
	),
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-campaign',
		'headline' => 'A campaign shot in three cities.',
		'category' => 'Photo & video',
		'year'     => '2026',
		'movements' => 'Identity, Production, Presence',
		'summary'  => 'Placeholder. A seasonal campaign produced across London, Paris and Dubai — replace with the real project.',
		'measures' => array( array( 'key' => 'CITIES', 'value' => '3' ), array( 'key' => 'ASSETS', 'value' => '120' ) ),
		'chapters' => array(
			array( 'title' => 'The direction', 'body' => 'Placeholder chapter. Describe the creative direction and why it fit the position.', 'mkey' => '', 'mval' => '' ),
			array( 'title' => 'The shoot', 'body' => 'Placeholder chapter. Describe the production itself.', 'mkey' => 'ASSETS', 'mval' => '120' ),
		),
	),
	array(
		'client'   => 'Client Name',
		'slug'     => 'placeholder-relaunch',
		'headline' => 'A relaunch that kept the customers it had.',
		'category' => 'Repositioning',
		'year'     => '2025',
		'movements' => 'Strategy, Identity, Presence',
		'summary'  => 'Placeholder. A brand relaunch and repositioning for a business that had grown by addition for nine years.',
		'measures' => array( array( 'key' => 'RANGE', 'value' => '−60%' ), array( 'key' => 'AOV', 'value' => '+38%' ) ),
		'chapters' => array(
			array( 'title' => 'The cut', 'body' => 'Placeholder chapter. Describe what was removed and how that decision was made.', 'mkey' => 'RANGE', 'mval' => '−60%' ),
		),
		'position' => array(
			'statement' => 'Placeholder repositioning line — replace with the real one.',
			'rejected'  => array( 'Placeholder alternative one', 'Placeholder alternative two', 'Placeholder alternative three' ),
		),
	),
);

foreach ( $cases as $i => $c ) {
	$meta = array(
		'ak_headline'  => $c['headline'],
		'ak_category'  => $c['category'],
		'ak_year'      => $c['year'],
		'ak_movements' => $c['movements'],
		'ak_summary'   => $c['summary'],
		'ak_measures'  => json_encode( $c['measures'], JSON_UNESCAPED_UNICODE ),
		'ak_chapters'  => json_encode( $c['chapters'], JSON_UNESCAPED_UNICODE ),
	);
	if ( isset( $c['position'] ) ) {
		$meta['ak_position'] = json_encode( $c['position'], JSON_UNESCAPED_UNICODE );
	}
	$case_body = '<p>Placeholder case narrative — replace with the project story. The chapters, measures and position blocks above are driven from the case fields.</p>'
		. "\n\n" . '<p>This project ran through the ' . movement_links( $c['movements'] ) . ' movement' . ( false === strpos( $c['movements'], ',' ) ? '' : 's' ) . '. '
		. 'Browse <a href="/work/">all work</a>, or <a href="/contact/">start a project</a>.</p>';
	list( , $xml ) = item(
		array(
			'title'   => $c['client'],
			'slug'    => $c['slug'],
			'type'    => 'portfolio',
			'content' => $case_body,
			'excerpt' => $c['summary'],
			'date'    => gmdate( 'Y-m-d H:i:s', strtotime( NOW ) - $i * 86400 ),
			'meta'    => $meta,
			'terms'   => array( array( 'project-categories', sanitize_slug( $c['category'] ), $c['category'] ) ),
		)
	);
	$items .= $xml;
}

function movement_links( $movements ) {
	$parts = array();
	foreach ( array_map( 'trim', explode( ',', $movements ) ) as $m ) {
		$anchor  = strtolower( $m );
		$parts[] = in_array( $anchor, array( 'strategy', 'identity', 'production', 'presence' ), true )
			? '<a href="/services/#' . $anchor . '">' . $m . '</a>'
			: $m;
	}
	$last = array_pop( $parts );
	return $parts ? implode( ', ', $parts ) . ' and ' . $last : $last;
}

function sanitize_slug( $s ) {
	$s = strtolower( trim( $s ) );
	$s = preg_replace( '/[^a-z0-9]+/', '-', $s );
	return trim( $s, '-' );
}

/* ── Journal posts ─────────────────────────────────────────────────────── */

$posts = array(
	array(
		'title'   => 'What it actually costs to show at a fashion week',
		'slug'    => 'what-it-costs-to-show-at-a-fashion-week',
		'cat'     => 'Production',
		'excerpt' => 'Placeholder standfirst. The real version should be the honest breakdown a young designer cannot find anywhere else — venue, casting, production, PR, and what a slot is genuinely worth.',
	),
	array(
		'title'   => 'Design the identity at ad size first',
		'slug'    => 'design-the-identity-at-ad-size-first',
		'cat'     => 'Identity',
		'excerpt' => 'Placeholder standfirst. A logo that only works at billboard scale is a logo that will be cropped, shrunk and ignored by the algorithm that decides whether anyone sees it.',
	),
	array(
		'title'   => 'Your company is not your personal brand',
		'slug'    => 'your-company-is-not-your-personal-brand',
		'cat'     => 'Strategy',
		'excerpt' => 'Placeholder standfirst. Why founders in fashion are usually better known than their labels — and what to do when it is the other way round.',
	),
	array(
		'title'   => 'Fix the website before you buy the traffic',
		'slug'    => 'fix-the-website-before-you-buy-the-traffic',
		'cat'     => 'Presence',
		'excerpt' => 'Placeholder standfirst. Every pound of promotion lands on a page. If that page is slow or unclear, promotion just buys a faster exit.',
	),
);

foreach ( $posts as $i => $p ) {
	$body = '<p>' . esc_body( $p['excerpt'] ) . '</p>' .
		"\n\n<p>Placeholder body. Replace with the full note — 600–900 words in the studio's voice. Subheadings set themselves in the display face automatically.</p>" .
		"\n\n" . '<p>Related: this note belongs to the ' . movement_links( $p['cat'] ) . ' movement. '
		. 'See it applied in <a href="/work/">the work</a>, read <a href="/about/">who is behind the studio</a>, or <a href="/contact/">start a project</a>.</p>';
	list( , $xml ) = item(
		array(
			'title'   => $p['title'],
			'slug'    => $p['slug'],
			'type'    => 'post',
			'content' => $body,
			'excerpt' => $p['excerpt'],
			'date'    => gmdate( 'Y-m-d H:i:s', strtotime( NOW ) - ( $i + 1 ) * 604800 ),
			'terms'   => array( array( 'category', sanitize_slug( $p['cat'] ), $p['cat'] ) ),
		)
	);
	$items .= $xml;
}

function esc_body( $s ) {
	return htmlspecialchars( (string) $s, ENT_NOQUOTES, 'UTF-8' );
}

/* ── Contact Form 7: the project brief ─────────────────────────────────── */

$form_body = <<<FORM
<div class="ak-grid-2">
<label class="ak-field"><span class="ak-field__label">Your name *</span>
    [text* your-name autocomplete:name] </label>

<label class="ak-field"><span class="ak-field__label">Email *</span>
    [email* your-email autocomplete:email] </label>
</div>

<div class="ak-grid-2">
<label class="ak-field"><span class="ak-field__label">Brand or company</span>
    [text your-brand autocomplete:organization] </label>

<label class="ak-field"><span class="ak-field__label">Website or Instagram</span>
    [text your-link] </label>
</div>

<label class="ak-field"><span class="ak-field__label">Where is the brand now? *</span>
    [select* brand-stage "Just an idea" "Launching — first collection or first product" "Trading — selling, but growth is flat" "Scaling — growing, and the seams are showing"] </label>

<label class="ak-field"><span class="ak-field__label">What do you think you need? *</span>
    [select* project-need "Brand strategy and positioning" "Personal brand" "Identity and creative direction" "Marketing and communication" "Photo / video campaign" "Event or fashion show production" "Website or online store" "Digital promotion" "Not sure — tell me what I need"] </label>

<label class="ak-field"><span class="ak-field__label">Tell us about the project *</span>
    [textarea* your-message] </label>

[submit "Send the brief"]
FORM;

$mail = array(
	'active'             => true,
	'subject'            => '[AK Studio] Project brief — [your-name]',
	'sender'             => '[_site_title] <wordpress@[_site_domain]>',
	'recipient'          => EMAIL,
	'body'               => "From: [your-name] <[your-email]>\nBrand: [your-brand]\nLink: [your-link]\n\nStage: [brand-stage]\nNeeds: [project-need]\n\n[your-message]\n\n--\nSent from [_site_title] ([_site_url])",
	'additional_headers' => 'Reply-To: [your-email]',
	'attachments'        => '',
	'use_html'           => false,
	'exclude_blank'      => false,
);

$mail_2 = array(
	'active'             => true,
	'subject'            => 'AK Brand Development Studio — we received your brief',
	'sender'             => '[_site_title] <wordpress@[_site_domain]>',
	'recipient'          => '[your-email]',
	'body'               => "Thank you — your brief has reached the studio.\n\nWe reply within two working days with an honest read: which movements your project actually needs, and which it does not.\n\nAK Brand Development Studio\nFashion & Brand Advisory — London\n[_site_url]",
	'additional_headers' => 'Reply-To: ' . EMAIL,
	'attachments'        => '',
	'use_html'           => false,
	'exclude_blank'      => false,
);

$messages = array(
	'mail_sent_ok'             => 'Sent. We reply within two working days.',
	'mail_sent_ng'             => 'Something failed on our side. Email hello@akbrand.studio directly.',
	'validation_error'         => 'A field or two needs attention below.',
	'spam'                     => 'The form could not verify this submission.',
	'accept_terms'             => 'Please accept the terms to continue.',
	'invalid_required'         => 'This field is required.',
	'invalid_too_long'         => 'This field is too long.',
	'invalid_too_short'        => 'This field is too short.',
	'upload_failed'            => 'Upload failed.',
	'upload_file_type_invalid' => 'This file type is not allowed.',
	'upload_file_too_large'    => 'This file is too large.',
	'upload_failed_php_error'  => 'Upload failed.',
	'invalid_date'             => 'Date format seems invalid.',
	'date_too_early'           => 'This date is too early.',
	'date_too_late'            => 'This date is too late.',
	'invalid_number'           => 'Number format seems invalid.',
	'number_too_small'         => 'This number is too small.',
	'number_too_large'         => 'This number is too large.',
	'quiz_answer_not_correct'  => 'The answer to the quiz is incorrect.',
	'invalid_email'            => 'This email address seems invalid.',
	'invalid_url'              => 'This URL seems invalid.',
	'invalid_tel'              => 'This telephone number seems invalid.',
);

list( , $xml ) = item(
	array(
		'title' => 'AK — Project brief',
		'slug'  => 'ak-project-brief',
		'type'  => 'wpcf7_contact_form',
		'meta'  => array(
			'_form'                => $form_body,
			'_mail'                => serialize( $mail ),
			'_mail_2'              => serialize( $mail_2 ),
			'_messages'            => serialize( $messages ),
			'_additional_settings' => '',
			'_locale'              => 'en_GB',
		),
	)
);
$items .= $xml;

/* ── Menu ──────────────────────────────────────────────────────────────── */

$menu_targets = array(
	array( 'Home', 'home' ),
	array( 'Work', 'work' ),
	array( 'Services', 'services' ),
	array( 'Journal', 'journal' ),
	array( 'About', 'about' ),
	array( 'Contact', 'contact' ),
);

foreach ( $menu_targets as $i => $m ) {
	list( , $xml ) = item(
		array(
			'title'      => $m[0],
			'slug'       => sanitize_slug( $m[0] ) . '-menu-item',
			'type'       => 'nav_menu_item',
			'menu_order' => $i + 1,
			'terms'      => array( array( 'nav_menu', 'primary', 'Primary' ) ),
			'meta'       => array(
				'_menu_item_type'             => 'post_type',
				'_menu_item_menu_item_parent' => '0',
				'_menu_item_object_id'        => (string) $page_ids[ $m[1] ],
				'_menu_item_object'           => 'page',
				'_menu_item_target'           => '',
				'_menu_item_classes'          => 'a:1:{i:0;s:0:"";}',
				'_menu_item_xfn'              => '',
				'_menu_item_url'              => '',
			),
		)
	);
	$items .= $xml;
}

/* ── Document ──────────────────────────────────────────────────────────── */

$header = <<<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  AK Brand Development Studio — content import.
  Import via Tools → Import → WordPress (with the child theme already active,
  so the portfolio post type exists to receive the case studies).
-->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
	<title>AK Brand Development Studio</title>
	<link>https://akbrand.studio</link>
	<description>Fashion &#38; Brand Advisory</description>
	<pubDate>Mon, 31 Aug 2026 12:00:00 +0000</pubDate>
	<language>en-GB</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>https://akbrand.studio</wp:base_site_url>
	<wp:base_blog_url>https://akbrand.studio</wp:base_blog_url>
	<wp:author>
		<wp:author_id>1</wp:author_id>
		<wp:author_login><![CDATA[akstudio]]></wp:author_login>
		<wp:author_email><![CDATA[hello@akbrand.studio]]></wp:author_email>
		<wp:author_display_name><![CDATA[AK Studio]]></wp:author_display_name>
		<wp:author_first_name><![CDATA[]]></wp:author_first_name>
		<wp:author_last_name><![CDATA[]]></wp:author_last_name>
	</wp:author>
	<wp:term>
		<wp:term_id>901</wp:term_id>
		<wp:term_taxonomy><![CDATA[nav_menu]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[primary]]></wp:term_slug>
		<wp:term_name><![CDATA[Primary]]></wp:term_name>
	</wp:term>

XML;

echo $header . $items . "</channel>\n</rss>\n";
